### ISSUE TITLE
/api/vehicle/{id}/changeLocation error 400 

### ISSUE THREAD

**Issue by magley** [asistenti/iss-swagger-spec#10]
One of the errors in `/api/vehicle/{id}/changeLocation` is: `400 | Vehicle is not assigned to the specific driver!`. If this refers to a driver trying to change some other driver's vehicle location, then the error code should be 404 as per the `README`. If this refers to a driver trying to change a vehicle assigned to nobody, then the error code should be the same as above, but either way this scenario is not possible as drivers have exactly one vehicle at all times and it never changes.

@greenenvy @lazer-nikolic

**Comment by asistenti** [comment]
Slazem se, bice ispravljeno u verziji 2.0.1
