### ISSUE TITLE
Password reset body

### ISSUE THREAD

**Issue by magley** [asistenti/iss-swagger-spec#11]
in `/user/resetPassword` or `/user/changePassword/`, the JSON key names should be in `camelCase`.
Furthermore, in the example request bodies, the passwords seem to be encoded (or at least, it's implied that they are, given the unusual rubbish string a la `"/(sFQ~&L\\? }{0/"`).

@greenenvy @lazer-nikolic

**Comment by magley** [comment]
Speaking of which, the password regex is too restrictive.

**Comment by asistenti** [comment]
Na poslu koristim python pretezno, pa sam se psihicki nisam prebacio na javu prilikom definicije endpoint-a. Bice ispravljeno u verziji 2.0.1

**Comment by asistenti** [comment]
A sto se tice ovog string-a, na redoc-u mi je prikazivalo taj regex u ispravnom obliku, provericu zasto swagger drugacije prikazuje. Verovatno je do escape-a odredjenih karaktera
