### ISSUE TITLE
Send message unnecessary ID field

### ISSUE THREAD

**Issue by magley** [asistenti/iss-swagger-spec#12]
In `POST /api/user/{id}/message`, the ID of the receiver is collected from the request body. It also says: `The sender is taken from the user that sent the request (from the token)`. Therefore, the path parameter `id` is redundant (or the field `receiverId` in the JSON is redundant).

@greenenvy @lazer-nikolic

**Comment by asistenti** [comment]
receiverId je visak. Bice korigovano u verziji 2.0.1 veceras.
