### ISSUE TITLE
GET Message returns paged response but has no page-related request parameters

### ISSUE THREAD

**Issue by swopl** [asistenti/iss-swagger-spec#13]
Missing page, size and that stuff. Or maybe it was intended to return a list of all of the messages?
Endpoint in question: GET /api/user/{id}/message

**Comment by asistenti** [comment]
U sustini ostavio bih ovako, jer mislim da ce vam svima lakse biti za implementaciju. Stvar je sto ako se tu uradi paginacija, onda ce vecina timova tu paginacijju na frontend-u morati da radi na scroll event-ove sto zna biti jako problematicno. Ok sam sa tim da se vrate sve poruke, jer idemo sa pretpostavkom da nece biti cesta komunikacija sa adminima, a totalCount je svakako info koji se moze iskorititi za frontend kod nekih timova. Tako da obe implementacije su mi ok i ovo ne bih dirao.

**Comment by swopl** [comment]
Moze
