### ISSUE TITLE
POST Driver vehicle should fail if driver already has a vehicle

### ISSUE THREAD

**Issue by magley** [asistenti/iss-swagger-spec#14]
Since a driver can have at most 1 vehicle at any given time (see `GET api/driver/{id}/vehicle`), the `POST api/driver/{id}/vehicle` endpoint should specify what happens if the driver already has a vehicle (e.g. `HTTP 400`).

@greenenvy @lazer-nikolic

**Comment by asistenti** [comment]
U principu dodela novog vozila se moze odraditi tako, sto ako vozac vec ima dodeljeno vozilo, da se isto pregazi, a staro vozilo da ostane nedodeljeno.

Naravno, ako imate neku drugaciju ideju, mozete dodati tu proveru pored postojecih. Ali je to vise implementacioni detalj koji vrlo zavisi, pa ga samim tim ne bih ubacivao u specifikaciju.
