### ISSUE TITLE
POST Message has extra id parameters somewhere

### ISSUE THREAD

**Issue by swopl** [asistenti/iss-swagger-spec#15]
The description states: 'The sender is taken from the user that sent the request (from the token)'
So i assume that is how we get senderId.
How about receiverId? It's in the example DTO.
But there is an extra id in the path: /api/user/{id}/message
Which id is this?
Should the DTO actually have receiverId or should we take receiverId from path?

**Comment by magley** [comment]
Related issue: #12

**Comment by asistenti** [comment]
receiverId je visak. Bice korigovano u verziji 2.0.1 veceras.

**Comment by swopl** [comment]
Closed as duplicate of #12
