### ISSUE TITLE
PUT /api/driver/working-hour/{working-hour-id}

### ISSUE THREAD

**Issue by magley** [asistenti/iss-swagger-spec#16]
In the endpoint `PUT /api/driver/working-hour/{working-hour-id}`, `working-hour-id` is a query parameter describing the working-hours object to modify. However, one of the expected scenarios for when the application should return `HTTP 400` is: `No shift is ongoing!`.
It doesn't make sense to check for a current shift if the modified working-hours object can be any of them, not just the last one. 

Should this scenario instead be `Shift is already completed`?

@greenenvy @lazer-nikolic

**Comment by asistenti** [comment]
Ovo isto zavisi dosta do implementacije. U principu ne bi trebalo da se dozvoli menjanje bilo kog radnog vremena vozacu, nego samo poslednjeg, pa ako poslednje referencirano radno vreme je takvo da je vec zavrseno, onda treba izbaciti gresku da ne postoji smena koja se moze zavrsiti. Gledajuci tako, onda id radnog vremena bi mogao biti visak, ali ako bi recimo admin u bilo kom trenutku menjao neke podatke o radnom vremenu, onda bi njemu bilo dozvoljeno i da retroaktivno vrsi neke korekcije, pa id u tom slucaju moze ostati.
