### ISSUE TITLE
Swagger has favorite rides instead of favorite locations

### ISSUE THREAD

**Issue by swopl** [asistenti/iss-swagger-spec#7]
There shouldn't be favorite rides (what would it even mean to have a favorite ride?) . Passengers have favorite locations
Read the title of point 2.11 in the ISS specification.
Also, 2.11 in the IKS specification implies that passengers can define favorite locations completely independently from their rides
Please fix

**Comment by asistenti** [comment]
Ovo nisam siguran da razumem. Tj. ne razumem sta je konfuzija, pa ako moze detaljnije objasnjenje sta je tacno problematicno.

**Comment by swopl** [comment]
Putnici na swagger-u imaju omiljene vožnje umesto omiljenih lokacija. U response body ima vožnja iako pise da vraća lokacije u opisu i u pdf specifikaciji

**Comment by asistenti** [comment]
Bitan je izgled JSON-a. Ako je u samom yml fajlu referenciran Ride, to je iz razloga da se ne bi jedan te isti kod vise puta pisao, tako da to zanemarite. Svi ti podaci koji se salju su nesto sto treba da olaksa korisniku da ponovo izabere istu konfiguraciju voznje koju je pre porucio. Znaci da ne mora da unosi sve ponovo vec da popuni u jednom kliku.

U pdf-u pise:
,,Obični korisnici prilikom poručivanja vožnje mogu označiti porudžbinu za omiljenu i da time dobiju mogućnost brzog biranja radi lakšeg poručivanja nove vožnje.,,

**Comment by swopl** [comment]
Pise u ISS specifikaciji "2.11. Definisanje omiljenih Lokacija". Naslov sugeriše omiljenu lokaciju. Taj paragraf ispod izgleda kao da nije bio update-ovan. Slican problem je bio na mobilnim gde neka mesta nisu bila update-ovana a neka jesu.
U IKS: "2.11 Korisnik može da definiše omiljenu lokaciju (lokacija i destinacija npr. kuća, posao)."
I na pitanja iz IKS-a da li su omiljene lokacije vise puta je rečeno nešto ovog oblika: da je bila izmenjena čitava specifikacija da nemamo više omiljene rute već omiljene destinacije.
Izgleda kao da su destinacije omiljene. Ako je tako, nije moguće sve informacije za brzo ponovno pokretanje vožnje odmah popuniti.
Ako hoćemo da sve bude popunjeno, trebaće nam omiljene rute. Ali to je bilo u staroj specifikaciji. Izmenjeno je da ne bude više tako. Šta sad da se radi? Bilo je bolje pre, ali sad zvanično gledaju za lokacije

**Comment by asistenti** [comment]
A ono sto sam pricao vec vise puta. Ta korekcija specifikacije je uopste bila nepotrebna, sto ste verovatno i sami skontali, jer nije nista problematicno. Ali nismo ni ja, ni Lazar inicirali tu promenu, cak smo i skrenuli paznju da ce to vise problema napraviti, no sad kako je tako je.

Trebalo bi da je moguce pokrenuti porucivanje voznje cim se popuni preko izbora vec sacuvane od pre. Dakle vrlo je minorna razlika od samog porucivanja voznje. Sama ruta se ne bira i ne mora da se iscrtava (to je ono sto je i izbaceno), tj. koordinate su vam samo i iskljucivo bitne kod simulacije kretanja vozila po mapi. Ali je to nesto sto mozete dobaviti u locust skripti i drzati te vrednosti tamo jer su koordinate potrebne pri simulaciji.

**Comment by swopl** [comment]
Ok. Znači implementirati omiljene rute (tj. sve informacije za ponovno pokretanje) umesto samo omiljenih lokacija?

**Comment by asistenti** [comment]
Da.

**Comment by swopl** [comment]
Hvala na pojašnjenju
