### ISSUE TITLE
Route estimation payload should include total distance

### ISSUE THREAD

**Issue by magley** [asistenti/iss-swagger-spec#8]
Consider changing the JSON body for `POST api/unregisteredUser` from 
```json
{
  "locations": [
    {
      "departure": {
        ...
      },
      "destination": {
        ...
      }
    }
  ],
  "vehicleType": "STANDARD",
  "babyTransport": true,
  "petTransport": true,
}
```
to
```json
{
  "locations": [
    {
      "departure": {
        ...
      },
      "destination": {
        ...
      }
    }
  ],
  "vehicleType": "STANDARD",
  "babyTransport": true,
  "petTransport": true,
  "totalDistance": 337,
}
```
because we are using the public OSRM server for routing, calculating distance, travel time etc. If we make too many reqests in a given period of time, the server can blacklist our IP address.

Otherwise, please add more info on how we're supposed to calculate the route distance on the server-side.

@greenenvy @lazer-nikolic

**Comment by asistenti** [comment]
Ovo zavisi od toga koji servis se koristi. OSMR (konkretno ovaj koji je koriscen u primeru), kao i vecina tih routing servisa, uglavnom imaju ili hard limit ili rate limit ka njihovom api-u. Konsultovacu se sa Lazarom oko toga, ali najverovatnije cemo dodati u verziji 2.0.1

Elem, malo istrazite, ali trebalo bi da postoji mogucnost da mozete i vas routing server da podignete, posto vidim da imaju docker image sa 100M+ povlacenja (https://hub.docker.com/r/osrm/osrm-backend/).

**Comment by asistenti** [comment]
Na kraju mislim da zapravo nije neophodno dodati jer kad submit-ujete listu taacaka, sa bekenda isto mozete pozvati OSMR servis i dobiti adekvatne informacije posto iscrtavanje rute nije neophodno.

Ako je vama licno to neophodno i to vam drastinco olaksava posao, slobodno dodajte kod sebe, nece vam negativno uticati na testove.
