### ISSUE TITLE
Ride /start is redundant

### ISSUE THREAD

**Issue by magley** [asistenti/iss-swagger-spec#9]
Is the endpoint `api/ride/{id}/start` not unnecessary?

The project specification states that once found, a driver is automatically assigned to a ride (see 1.4) On that note, a driver can "reject" a ride by clicking on the "cancel" button (`api/ride/{id}/cancel`), which he can do only do while the ride is in `PENDING` state. This means that an accepted (`ACCEPTED`, not `STARTED`) ride cannot be rejected/canceled which means that between the moment of accepting a ride and starting it, the driver cannot change his mind. For a ride scheduled in the future, this is not a desired way of doing things.

Without the 'STARTED' state, it's simply up to the driver to click `cancel` (`api/ride/{id}/cancel`, see 2.5) or `accept` (which **begins** the ride, see 2.6). Each of these scenarios has one ride-state mapped to it (`pending`, `canceled`, `accepted`).

@greenenvy @lazer-nikolic

**Comment by asistenti** [comment]
Posto postoji mogucnost da i korisnik odradi povlacenje voznje, ideja kod start stanja je da postoji to medjustanje do kog putnik moze otkazati voznju.  Dakle od trenutka kad je porucio voznju, do trenutka kada je voznja pocela, on moze da otkaze u bilo kom trenutku, kao sto je situacija i sa nasim taskijima (recimo pan i crveni). Ako nemamo started stanje, onda mozemo da podrazumevamo da je trenutak kada on to vise ne moze otakzati, onda kada se dodeli vozilo, ali time putnik ima manje prostora za otkazivanje.

**Comment by magley** [comment]
U tom slučaju `/ride/cancel` treba da bude omogućen i kada je vožnja u "Pending" i "Accepted" stanju (a ne samo "Pending"), jer odbijenica oblika "No passengers were at the destination" može samo da se napravi kada je vozač spreman da započne vožnju.

**Comment by asistenti** [comment]
Da, skrenuta mi je paznja na to od strane jos jednog tima, tako da i to sam vec ispravio i bice za par sati.
